services:
  api_monitor:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules   # แยก node_modules ของ container
    depends_on:
      - db
    command: npm run dev

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_db
    ports:
      - "3307:3306"   # host port 3307 map ไป container port 3306
    volumes:
      - mysqldata:/var/lib/mysql


volumes:
  mysqldata:
